### ISSUE TITLE
K

### ISSUE THREAD

**Issue by Jrpl1228** [MiguelFoliaco/store-theme-linio#1]
I

**Comment by Jrpl1228** [comment]
Como hago

**Comment by MiguelFoliaco** [comment]
@Jrpl1228  Puedes escribirme a este correo foliacosoft18@gmail.com

**Comment by Jrpl1228** [comment]
![Screenshot_20230903-032105_PUB File Viewer and Converter](https://github.com/MiguelFoliaco/store-theme-linio/assets/127596695/496f020e-bd9d-4ad5-9958-cadb9cd4f7b4)

**Comment by Jrpl1228** [comment]
![Screenshot_20230903-032105_PUB File Viewer and Converter](https://github.com/MiguelFoliaco/store-theme-linio/assets/127596695/a7bd67e9-a1c1-4213-805a-6fb652a258f4)

**Comment by Jrpl1228** [comment]
Que significa esto?
